# Generated by Django 4.2.19 on 2025-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0008_alter_sensordata_humidity_alter_sensordata_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
