# Generated by Django 4.2.19 on 2025-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0002_rename_received_sensordata_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17),
        ),
    ]
